# Generated by Django 5.0 on 2023-12-30 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Login", "0003_alter_blog_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=24)),
                (
                    "blogs",
                    models.ManyToManyField(related_name="user_blogs", to="Login.blog"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="blog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_set",
                to="Login.user",
            ),
        ),
    ]
