# Generated by Django 5.0 on 2023-12-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Login", "0005_alter_blog_user_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="Video",
            field=models.FileField(
                blank=True, null=True, upload_to="C:\\Users\\karan\\Desktop\\Videos"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="Image",
            field=models.ImageField(
                blank=True, null=True, upload_to="C:\\Users\\karan\\Desktop\\Images"
            ),
        ),
    ]
