# Generated by Django 5.0 on 2024-01-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Login", "0006_blog_video_alter_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="Image",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="Video",
            field=models.FileField(blank=True, null=True, upload_to="media/"),
        ),
    ]
