# Generated by Django 5.0 on 2024-01-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Login", "0007_alter_blog_image_alter_blog_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="Image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="Video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
