# Generated by Django 5.0 on 2023-12-26 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="blog",
        ),
    ]
